### ISSUE TITLE
Audio Recording issue

### ISSUE THREAD

**Issue by harisazam** [rjeffm/CallRecorder#2]
hi there,
i was looking in to code and functionality, you did a lot of effort in this and is working well except one thing. it does not record audio more then 1 sec. can you help please?

**Comment by anandinmaddy** [comment]
@harisazam please check you have more than one call recorder running in your phone. Sometimes it will block the receiver to run in background.

**Comment by gsbala04** [comment]
Hi,
      I downloaded your code and ran the app, But nothing happened. I did not see the recorded file in storage folder. It even not created the "calls" folder. Could you please clarify this.

**Comment by rjeffm** [comment]
It's possible it's a permissions issue. The code is for earlier versions of Android.
